name = "akamai-hook"
type = "webpack"

account_id = "ca7271d81a89aa1b584684f4aea8c1a4"
workers_dev = true
compatibility_date = "2021-11-15"

[vars]
# Get this value from your Upstash account.
UPSTASH_ENDPOINT = "https://eu1-artistic-bass-33019.upstash.io"

# [secrets]
# UPSTASH_TOKEN
# This is the value Okta will provide in the `Authorization` header.
# API_KEY
